'use strict';
const express=require('express');
const c=require('../controllers/vehiculoController');
const {requiereLogin}=require('../middleware/authMiddleware');
const router=express.Router();
router.use(requiereLogin);
router.get('/buscar',c.mostrarBusqueda);
router.post('/buscar',c.buscarPorPlaca);
router.get('/buscar-clientes',c.buscarClientes);
router.get('/nuevo',c.mostrarFormularioNuevo);
router.post('/',c.crear);
router.post('/:id/mantenimiento',c.actualizarMantenimiento);
router.get('/:id',c.verDetalle);
module.exports=router;
