'use strict';
const { Op } = require('sequelize');
const { OrdenTrabajo, EstadoOrden, Vehiculo, Cliente, OrdenRepuesto } = require('../models');
const gti = require('../data/gtiService');
function rangoQuincena(fecha=new Date()){const y=fecha.getFullYear(),m=fecha.getMonth(),d=fecha.getDate();return{inicio:new Date(y,m,d<=15?1:16,0,0,0,0),fin:d<=15?new Date(y,m,15,23,59,59,999):new Date(y,m+1,0,23,59,59,999)};}
function fechaLocal(v){if(!v)return null;const d=new Date(v+'T00:00:00');return Number.isNaN(d.getTime())?null:d;}
function inputDate(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`;}
exports.listar=async(req,res)=>{try{const def=rangoQuincena(),desde=fechaLocal(req.query.desde)||def.inicio,hastaBase=fechaLocal(req.query.hasta)||def.fin,hasta=new Date(hastaBase);hasta.setHours(23,59,59,999);const ordenes=await OrdenTrabajo.findAll({where:{fechaFin:{[Op.between]:[desde,hasta]}},include:[{model:EstadoOrden,as:'estado',where:{nombre:'Finalizada'}},{model:Vehiculo,as:'vehiculo',include:[{model:Cliente,as:'cliente'}]},{model:OrdenRepuesto,as:'repuestos',required:false}],order:[['fechaFin','ASC']]});const filas=ordenes.map(o=>{const repuestos=(o.repuestos||[]).reduce((s,r)=>s+(Number(r.cantidad)||0)*(Number(r.precio)||0)-(Number(r.descuento)||0),0),iva=repuestos*.13,servicio=Math.max(0,Number(o.manoObra||0)+Number(o.otros||0)-Number(o.descuento||0));return{orden:o,repuestos,iva,servicio,total:repuestos+iva+servicio};});const grupos={};for(const f of filas){const k=f.orden.responsableTrabajo||'Sin asignar';if(!grupos[k])grupos[k]={responsable:k,filas:[],servicios:0,total:0};grupos[k].filas.push(f);grupos[k].servicios+=f.servicio;grupos[k].total+=f.total;}return res.render('facturacionQuincenal',{titulo:'Facturación Quincenal',filas,grupos:Object.values(grupos),desde:inputDate(desde),hasta:inputDate(hasta),gtiConfigurado:gti.configurado()});}catch(e){console.error(e);return res.status(500).send('No fue posible cargar la facturación quincenal: '+e.message);}};
exports.enviarGTI=async(req,res)=>{try{const orden=await OrdenTrabajo.findByPk(Number(req.params.id),{include:[{model:Vehiculo,as:'vehiculo',include:[{model:Cliente,as:'cliente'}]},{model:OrdenRepuesto,as:'repuestos',required:false}]});if(!orden)return res.status(404).send('Orden no encontrada.');const resultado=await gti.enviarOrden(orden);await orden.update({gtiEstado:'enviada',gtiReferencia:resultado.referencia||resultado.id||resultado.clave||null});return res.redirect('/facturacion-quincenal');}catch(e){console.error(e);return res.status(502).send('GTI no pudo procesar la factura: '+e.message);}};
