'use strict';
const { Op } = require('sequelize');
const { OrdenTrabajo, EstadoOrden, Vehiculo, Cliente, OrdenRepuesto } = require('../models');
function rangoQuincena(fecha=new Date()){const y=fecha.getFullYear(),m=fecha.getMonth(),d=fecha.getDate();return{inicio:new Date(y,m,d<=15?1:16,0,0,0,0),fin:d<=15?new Date(y,m,15,23,59,59,999):new Date(y,m+1,0,23,59,59,999)};}
function fechaLocal(v){if(!v)return null;const d=new Date(v+'T00:00:00');return Number.isNaN(d.getTime())?null:d;}
function inputDate(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`;}
function etiquetaResponsable(o){const destino=String(o.destinoServicio||'').trim().toLowerCase();if(destino==='emerson'||String(o.responsableTrabajo||'').trim().toLowerCase()==='emerson')return'Emerson';return'Taller';}
function usuarioTaller(o){if(etiquetaResponsable(o)==='Emerson')return'';const mecanico=String(o.responsableTrabajo||'').trim();const cierre=String(o.finalizadoPor||'').trim();if(mecanico.toLowerCase()==='anderson')return'Anderson';if(/^rodolfo\b/i.test(cierre))return'Rodolfo';if(/^anderson\b/i.test(cierre))return'Anderson';return'';}
function quincenasHistorial(fecha=new Date(),cantidad=8){const out=[];for(let i=0;i<cantidad;i++){const d=new Date(fecha.getFullYear(),fecha.getMonth(),1);d.setMonth(d.getMonth()-Math.floor(i/2));const inicio=i%2===0?new Date(d.getFullYear(),d.getMonth(),16):new Date(d.getFullYear(),d.getMonth(),1);const fin=i%2===0?new Date(d.getFullYear(),d.getMonth()+1,0):new Date(d.getFullYear(),d.getMonth(),15);out.push({desde:inputDate(inicio),hasta:inputDate(fin),label:`${inicio.toLocaleDateString('es-CR')} — ${fin.toLocaleDateString('es-CR')}`});}return out;}
exports.listar=async(req,res)=>{try{const def=rangoQuincena(),desde=fechaLocal(req.query.desde)||def.inicio,hastaBase=fechaLocal(req.query.hasta)||def.fin,hasta=new Date(hastaBase);hasta.setHours(23,59,59,999);const ordenes=await OrdenTrabajo.findAll({where:{fechaFin:{[Op.between]:[desde,hasta]}},include:[{model:EstadoOrden,as:'estado',where:{nombre:'Finalizada'}},{model:Vehiculo,as:'vehiculo',include:[{model:Cliente,as:'cliente'}]},{model:OrdenRepuesto,as:'repuestos',required:false}],order:[['fechaFin','ASC']]});const filas=ordenes.map(o=>{const repuestos=(o.repuestos||[]).reduce((s,r)=>s+(Number(r.cantidad)||0)*(Number(r.precio)||0)-(Number(r.descuento)||0),0),iva=repuestos*.13,servicio=Math.max(0,Number(o.manoObra||0)+Number(o.otros||0)-Number(o.descuento||0));return{orden:o,repuestos,iva,servicio,total:repuestos+iva+servicio,usuarioTaller:usuarioTaller(o)};});const grupos={};for(const fila of filas){const k=etiquetaResponsable(fila.orden);if(!grupos[k])grupos[k]={responsable:k,filas:[],servicios:0,total:0};grupos[k].filas.push(fila);grupos[k].servicios+=fila.servicio;grupos[k].total+=fila.total;}return res.render('facturacionQuincenal',{titulo:'Facturación Quincenal',filas,grupos:Object.values(grupos),desde:inputDate(desde),hasta:inputDate(hasta),historial:quincenasHistorial(new Date(),8)});}catch(e){console.error(e);return res.status(500).send('No fue posible cargar la facturación quincenal: '+e.message);}};
