'use strict';
const { Op } = require('sequelize');
const { sequelize,Cliente,Vehiculo,OrdenTrabajo,EstadoOrden,OrdenTrabajoDetalle,OrdenRepuesto }=require('../models');
const volver=(res,vehiculoId,anchor='reparacion-actual')=>res.redirect(`/vehiculos/${vehiculoId}#${anchor}`);
async function listarActivas(req,res){try{const ordenes=await OrdenTrabajo.findAll({include:[{model:Vehiculo,as:'vehiculo',include:[{model:Cliente,as:'cliente'}]},{model:EstadoOrden,as:'estado'}],order:[['fechaRecepcion','DESC']]});return res.render('ordenes/ordenes',{titulo:'Lista de reparaciones',ordenes:ordenes.filter(o=>!['Entregada','Cancelada'].includes(o.estado?.nombre))});}catch(e){console.error(e);return res.status(500).send(e.message);}}
async function mostrarFormularioNuevo(req,res){const vehiculo=await Vehiculo.findByPk(Number(req.params.vehiculoId),{include:[{model:Cliente,as:'cliente'}]});if(!vehiculo)return res.status(404).send('Vehículo no encontrado.');return res.render('ordenes/nuevaOrden',{titulo:'Nueva reparación',vehiculo,orden:{kilometraje_ingreso:vehiculo.kilometrajeActual},errores:[]});}
async function crear(req,res){try{const vehiculo=await Vehiculo.findByPk(Number(req.params.vehiculoId));if(!vehiculo)return res.status(404).send('Vehículo no encontrado.');const km=Number(req.body.kilometraje_ingreso),problema=String(req.body.problema_reportado||'').trim();if(!Number.isFinite(km)||km<0||!problema)return res.status(400).send('Kilometraje y motivo de ingreso son obligatorios.');const estado=await EstadoOrden.findOne({where:{nombre:'Recibida'}});if(!estado)return res.status(500).send('Falta el estado Recibida.');await OrdenTrabajo.create({numeroOrden:await generarNumeroOrden(),vehiculoId:vehiculo.id,estadoId:estado.id,usuarioRecepcionaId:null,kilometrajeIngreso:km,problemaReportado:problema,observaciones:String(req.body.observaciones||'').trim()||null,prioridad:'Normal'});await vehiculo.update({kilometrajeActual:km});return volver(res,vehiculo.id);}catch(e){console.error(e);return res.status(500).send(e.message);}}
async function verDetalle(req,res){const orden=await OrdenTrabajo.findByPk(Number(req.params.id));if(!orden)return res.status(404).send('Orden no encontrada.');return volver(res,orden.vehiculoId);}
async function agregarTrabajo(req,res){try{const orden=await OrdenTrabajo.findByPk(Number(req.params.id));if(!orden)return res.status(404).send('Orden no encontrada.');const tipo=req.body.tipo==='realizado'?'realizado':'detectado';const entrada=String(req.body.descripcion||'').replace(/\r/g,'').trim();const lineas=entrada.split('\n').map(x=>x.replace(/^[-•✓*]\s*/,'').trim()).filter(Boolean);if(lineas.length)await OrdenTrabajoDetalle.bulkCreate(lineas.map(descripcion=>({ordenId:orden.id,usuarioId:null,descripcion,estado:tipo})));return volver(res,orden.vehiculoId,tipo==='detectado'?'lista-reparacion':'trabajo-realizado');}catch(e){console.error(e);return res.status(500).send('No fue posible guardar la lista.');}}
async function cambiarEstadoTrabajo(req,res){try{const trabajo=await OrdenTrabajoDetalle.findByPk(Number(req.params.trabajoId));if(!trabajo)return res.status(404).send('Trabajo no encontrado.');const orden=await OrdenTrabajo.findByPk(trabajo.ordenId);if(!orden)return res.status(404).send('Orden no encontrada.');const realizado=req.body.realizado==='1';await trabajo.update({estado:realizado?'realizado':'detectado',fechaFin:realizado?new Date():null});return volver(res,orden.vehiculoId,'lista-reparacion');}catch(e){console.error(e);return res.status(500).send('No fue posible actualizar el trabajo.');}}
async function agregarRepuesto(req,res){try{const orden=await OrdenTrabajo.findByPk(Number(req.params.id));if(!orden)return res.status(404).send('Orden no encontrada.');const descripcion=String(req.body.descripcion||'').trim();if(descripcion)await OrdenRepuesto.create({ordenId:orden.id,descripcion,cantidad:Math.max(Number(req.body.cantidad)||1,0.01),precio:Math.max(Number(req.body.precio)||0,0),descuento:0});return volver(res,orden.vehiculoId,'repuestos');}catch(e){console.error(e);return res.status(500).send('No fue posible agregar el repuesto.');}}
async function agregarRepuestoDesdeTrabajo(req,res){try{const trabajo=await OrdenTrabajoDetalle.findByPk(Number(req.params.trabajoId));if(!trabajo)return res.status(404).send('Trabajo no encontrado.');const orden=await OrdenTrabajo.findByPk(trabajo.ordenId);if(!orden)return res.status(404).send('Orden no encontrada.');const existe=await OrdenRepuesto.findOne({where:{ordenId:orden.id,descripcion:trabajo.descripcion}});if(!existe)await OrdenRepuesto.create({ordenId:orden.id,descripcion:trabajo.descripcion,cantidad:1,precio:0,descuento:0});return volver(res,orden.vehiculoId,'repuestos');}catch(e){console.error(e);return res.status(500).send('No fue posible pasar el elemento a repuestos.');}}
async function agregarTodosRepuestos(req,res){try{const orden=await OrdenTrabajo.findByPk(Number(req.params.id));if(!orden)return res.status(404).send('Orden no encontrada.');const [trabajos,repuestos]=await Promise.all([OrdenTrabajoDetalle.findAll({where:{ordenId:orden.id}}),OrdenRepuesto.findAll({where:{ordenId:orden.id}})]);const existentes=new Set(repuestos.map(r=>String(r.descripcion||'').trim().toLowerCase()));const nuevos=trabajos.filter(t=>!existentes.has(String(t.descripcion||'').trim().toLowerCase())).map(t=>({ordenId:orden.id,descripcion:t.descripcion,cantidad:1,precio:0,descuento:0}));if(nuevos.length)await OrdenRepuesto.bulkCreate(nuevos);return volver(res,orden.vehiculoId,'repuestos');}catch(e){console.error(e);return res.status(500).send('No fue posible agregar todos los elementos al cobro.');}}
async function actualizarRepuesto(req,res){try{const repuesto=await OrdenRepuesto.findByPk(Number(req.params.repuestoId));if(!repuesto)return res.status(404).send('Repuesto no encontrado.');const orden=await OrdenTrabajo.findByPk(repuesto.ordenId);if(!orden)return res.status(404).send('Orden no encontrada.');const descripcion=String(req.body.descripcion||'').trim(),cantidad=Number(req.body.cantidad),precio=Number(req.body.precio);if(!descripcion||!Number.isFinite(cantidad)||cantidad<=0||!Number.isFinite(precio)||precio<0)return res.status(400).send('Descripción, cantidad y precio no son válidos.');await repuesto.update({descripcion,cantidad,precio});return volver(res,orden.vehiculoId,'repuestos');}catch(e){console.error(e);return res.status(500).send('No fue posible actualizar el repuesto.');}}
async function limpiarTrabajos(req,res){try{const orden=await OrdenTrabajo.findByPk(Number(req.params.id));if(!orden)return res.status(404).send('Orden no encontrada.');await OrdenTrabajoDetalle.destroy({where:{ordenId:orden.id}});return volver(res,orden.vehiculoId,'lista-reparacion');}catch(e){console.error(e);return res.status(500).send('No fue posible limpiar la lista.');}}
async function limpiarCobro(req,res){try{const orden=await OrdenTrabajo.findByPk(Number(req.params.id));if(!orden)return res.status(404).send('Orden no encontrada.');await sequelize.transaction(async t=>{await OrdenRepuesto.destroy({where:{ordenId:orden.id},transaction:t});await orden.update({manoObra:0,otros:0,descuento:0},{transaction:t});});return volver(res,orden.vehiculoId,'repuestos');}catch(e){console.error(e);return res.status(500).send('No fue posible limpiar el cobro.');}}
async function limpiarDetalle(req,res){try{const orden=await OrdenTrabajo.findByPk(Number(req.params.id));if(!orden)return res.status(404).send('Orden no encontrada.');await sequelize.transaction(async t=>{await OrdenTrabajoDetalle.destroy({where:{ordenId:orden.id},transaction:t});await OrdenRepuesto.destroy({where:{ordenId:orden.id},transaction:t});await orden.update({manoObra:0,otros:0,descuento:0},{transaction:t});});return volver(res,orden.vehiculoId,'reparacion-actual');}catch(e){console.error(e);return res.status(500).send('No fue posible limpiar el detalle.');}}
async function actualizarTotales(req,res){const orden=await OrdenTrabajo.findByPk(Number(req.params.id));if(!orden)return res.status(404).send('Orden no encontrada.');await orden.update({manoObra:Number(req.body.mano_obra)||0,otros:Number(req.body.otros)||0,descuento:Number(req.body.descuento)||0});return volver(res,orden.vehiculoId,'cuenta-taller');}
async function finalizar(req,res){try{const orden=await OrdenTrabajo.findByPk(Number(req.params.id));if(!orden)return res.status(404).send('Orden no encontrada.');const responsable=String(req.body.responsable_trabajo||'').trim();if(!responsable)return volver(res,orden.vehiculoId,'finalizar-reparacion');const estado=await EstadoOrden.findOrCreate({where:{nombre:'Finalizada'},defaults:{nombre:'Finalizada'}});const sesion=req.session?.usuario;const finalizadoPor=sesion?.nombre||sesion?.usuario||'Sistema Casteli';await orden.update({estadoId:estado[0].id,fechaFin:new Date(),responsableTrabajo:responsable,finalizadoPor});return res.redirect('/ordenes');}catch(e){console.error(e);return res.status(500).send('No fue posible finalizar la reparación.');}}
async function generarNumeroOrden(){const anio=new Date().getFullYear();const ultima=await OrdenTrabajo.findOne({where:{numeroOrden:{[Op.like]:`OT-${anio}-%`}},order:[['id','DESC']]});const n=ultima?Number(ultima.numeroOrden.split('-')[2]||0)+1:1;return `OT-${anio}-${String(n).padStart(4,'0')}`;}
module.exports={listarActivas,mostrarFormularioNuevo,crear,verDetalle,agregarTrabajo,cambiarEstadoTrabajo,agregarRepuesto,agregarRepuestoDesdeTrabajo,agregarTodosRepuestos,actualizarRepuesto,limpiarTrabajos,limpiarCobro,limpiarDetalle,actualizarTotales,finalizar};